 CREATE TABLE STUDENTS(id INT primary key,name VARCHAR(20),age INT,course VARCHAR(20));

 INSERT INTO STUDENTS(id ,name ,age ,course)VALUES(2,'HRITHIK',20,'COMPUTER_SCIENCE'),(3,'UJWAL',23,'INFORMATION TECHNOLOGY'),(4,'BHUVAN',30,'ROBOTICS'),(5,'SWEEKAR',25,'ARTIFICIAL TECHNOLOGY'),(6,'RAVI KUMAR',24,'COMPUTER_SCIENCE');
  
 SELECT * FROM STUDENTS WHERE course='INFORMATION TECHNOLOGY';
 
 UPDATE STUDENTS SET course ='MECHANICAL' WHERE id=3;
 
 DELETE FROM STUDENTS WHERE name='RAVI KUMAR';

 SELECT * FROM STUDENTS ;